/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/use-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search and filter published use cases */
        get: operations["list_use_cases_v1_use_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/use-case-facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filter options */
        get: operations["facets_v1_use_case_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/use-cases-sitemap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Slugs for sitemaps */
        get: operations["sitemap_v1_use_cases_sitemap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/use-cases/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One published use case */
        get: operations["detail_v1_use_cases__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/use-cases/preview/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A draft for review (signed preview token) */
        get: operations["preview_v1_use_cases_preview__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiError */
        ApiError: {
            /** Detail */
            detail: string;
        };
        /** CategoryFacet */
        CategoryFacet: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Count */
            count: number;
        };
        /** CategoryRef */
        CategoryRef: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
        };
        /** Facets */
        Facets: {
            /** Total */
            total: number;
            /** Categories */
            categories: components["schemas"]["CategoryFacet"][];
            /** Tags */
            tags: components["schemas"]["TagFacet"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Sitemap */
        Sitemap: {
            /** Items */
            items: components["schemas"]["SitemapEntry"][];
            /** Total */
            total: number;
            /** Chunks */
            chunks: number;
            /** Chunk */
            chunk: number;
        };
        /** SitemapEntry */
        SitemapEntry: {
            /** Slug */
            slug: string;
            /** Updated At */
            updated_at: string;
        };
        /** TagFacet */
        TagFacet: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Count */
            count: number;
        };
        /** TagRef */
        TagRef: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
        };
        /** UseCaseCard */
        UseCaseCard: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Industry */
            industry: string;
            /** Audience */
            audience: string;
            /** Task Type */
            task_type: string;
            /** Question Types */
            question_types: ("choice" | "noul" | "score")[];
            /** Has Demo */
            has_demo: boolean;
            category: components["schemas"]["CategoryRef"] | null;
            /** Tags */
            tags: components["schemas"]["TagRef"][];
            /** Published At */
            published_at: string | null;
            /** Updated At */
            updated_at: string;
        };
        /** UseCaseDetail */
        UseCaseDetail: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Industry */
            industry: string;
            /** Audience */
            audience: string;
            /** Task Type */
            task_type: string;
            /** Question Types */
            question_types: ("choice" | "noul" | "score")[];
            /** Has Demo */
            has_demo: boolean;
            category: components["schemas"]["CategoryRef"] | null;
            /** Tags */
            tags: components["schemas"]["TagRef"][];
            /** Published At */
            published_at: string | null;
            /** Updated At */
            updated_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "published";
            /**
             * Page
             * @description The complete verified page: prose, examples, demo.
             */
            page: {
                [key: string]: unknown;
            };
            /** Related */
            related: components["schemas"]["UseCaseCard"][];
        };
        /** UseCaseList */
        UseCaseList: {
            /** Items */
            items: components["schemas"]["UseCaseCard"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_use_cases_v1_use_cases_get: {
        parameters: {
            query?: {
                /** @description Full-text search */
                q?: string | null;
                category?: string | null;
                tag?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UseCaseList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    facets_v1_use_case_facets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Facets"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    sitemap_v1_use_cases_sitemap_get: {
        parameters: {
            query?: {
                chunk?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sitemap"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    detail_v1_use_cases__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UseCaseDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    preview_v1_use_cases_preview__slug__get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UseCaseDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
