import type { Preset } from "./typesafe";

export const PRESETS: Preset[] = [
  {
    id: "route-support",
    title: "Sort support messages",
    description: "Send a customer to the right kind of help, without reading every message by hand.",
    group: "support",
    type: "choice",
    icon: "mail",
    questionId: "request_type",
    instructions: "What is the customer asking about?",
    criteria: {
      refund: "The customer wants money returned for an order.",
      delivery: "The customer asks about shipping, tracking, or when an order will arrive.",
      other: "A question that is not about a refund or delivery.",
    },
    from: "customer message",
    to: "refund",
    tags: "email classify label route ticket help billing",
    variants: [
      {
        name: "A refund",
        state: "Hi! I ordered the blue trainers, but they don't fit. Could I get my money back?",
        answer: {
          type: "choice",
          choice: "refund",
          probabilities: { refund: 0.94, delivery: 0.04, other: 0.02 },
          confidence: 0.88,
        },
        next: "Open the refund-help flow. Let your policy decide eligibility.",
      },
      {
        name: "Delivery",
        state: "My order was due yesterday. Do you know when it will arrive?",
        answer: {
          type: "choice",
          choice: "delivery",
          probabilities: { refund: 0.02, delivery: 0.96, other: 0.02 },
          confidence: 0.91,
        },
        next: "Show order tracking, or send the message to delivery support.",
      },
      {
        name: "Something else",
        state: "Are the blue trainers available in a size six?",
        answer: {
          type: "choice",
          choice: "other",
          probabilities: { refund: 0.02, delivery: 0.03, other: 0.95 },
          confidence: 0.89,
        },
        next: "Pass this to general support rather than guessing a category.",
      },
    ],
  },
  {
    id: "spot-urgency",
    title: "Spot an urgent message",
    description: "Notice time-sensitive messages so they can get a closer look sooner.",
    group: "support",
    type: "noul",
    icon: "zap",
    questionId: "is_urgent",
    instructions: "Does this message describe a problem that needs attention immediately or by a near deadline?",
    criteria: {
      true: "The message states an immediate problem or a near deadline.",
      false: "The message is routine or explicitly says there is no rush.",
    },
    from: "a message",
    to: "yes probability",
    tags: "priority urgent time email inbox noul flag",
    variants: [
      {
        name: "Urgent",
        state: "Our checkout stopped working and customers can't pay. We need help right now.",
        answer: { type: "noul", noul: 0.98 },
        next: "Flag this for a person to review promptly.",
      },
      {
        name: "Not urgent",
        state: "No rush, but could you explain how I change the colour of my profile?",
        answer: { type: "noul", noul: 0.04 },
        next: "Leave this in the regular support queue.",
      },
      {
        name: "Less clear",
        state: "Could somebody look at my account soon? It has been a little strange.",
        answer: { type: "noul", noul: 0.54 },
        next: "Ask for more context instead of treating an uncertain answer as a yes.",
      },
    ],
  },
  {
    id: "rate-review",
    title: "Understand a review",
    description: "Put feedback on a scale, from unhappy to delighted, using levels you define.",
    group: "everyday",
    type: "score",
    icon: "star",
    questionId: "review_sentiment",
    instructions: "How positive or negative is the review about the product?",
    criteria: [
      "Strongly negative: the reviewer is very unhappy and advises against buying.",
      "Mostly negative: the reviewer mentions more problems than benefits.",
      "Mixed or neutral: positives and negatives are balanced, or no opinion is given.",
      "Mostly positive: the reviewer likes the product but mentions a drawback.",
      "Strongly positive: the reviewer is delighted and clearly recommends the product.",
    ],
    from: "product review",
    to: "a score",
    tags: "sentiment rating score positive negative feedback reviews ecommerce",
    variants: [
      {
        name: "Delighted",
        state: "These headphones are brilliant. Clear sound, comfy all day, and the battery lasts ages. I'd definitely recommend them!",
        answer: {
          type: "score",
          score: 3.86,
          legend: {
            "0": "Strongly negative: the reviewer is very unhappy and advises against buying.",
            "1": "Mostly negative: the reviewer mentions more problems than benefits.",
            "2": "Mixed or neutral: positives and negatives are balanced, or no opinion is given.",
            "3": "Mostly positive: the reviewer likes the product but mentions a drawback.",
            "4": "Strongly positive: the reviewer is delighted and clearly recommends the product.",
          },
          probabilities: { "0": 0, "1": 0.01, "2": 0.01, "3": 0.09, "4": 0.89 },
          confidence: 0.83,
        },
        next: "Group this with positive feedback while keeping the original review.",
      },
      {
        name: "Mixed",
        state: "The sound is great, but they start to feel uncomfortable after an hour. Some things are good, some aren't.",
        answer: {
          type: "score",
          score: 1.99,
          legend: {
            "0": "Strongly negative: the reviewer is very unhappy and advises against buying.",
            "1": "Mostly negative: the reviewer mentions more problems than benefits.",
            "2": "Mixed or neutral: positives and negatives are balanced, or no opinion is given.",
            "3": "Mostly positive: the reviewer likes the product but mentions a drawback.",
            "4": "Strongly positive: the reviewer is delighted and clearly recommends the product.",
          },
          probabilities: { "0": 0.01, "1": 0.12, "2": 0.75, "3": 0.11, "4": 0.01 },
          confidence: 0.64,
        },
        next: "Keep this as mixed feedback, not simply positive or negative.",
      },
      {
        name: "Disappointed",
        state: "They stopped working after two days. A complete waste of money. I really wouldn't recommend them.",
        answer: {
          type: "score",
          score: 0.07,
          legend: {
            "0": "Strongly negative: the reviewer is very unhappy and advises against buying.",
            "1": "Mostly negative: the reviewer mentions more problems than benefits.",
            "2": "Mixed or neutral: positives and negatives are balanced, or no opinion is given.",
            "3": "Mostly positive: the reviewer likes the product but mentions a drawback.",
            "4": "Strongly positive: the reviewer is delighted and clearly recommends the product.",
          },
          probabilities: { "0": 0.94, "1": 0.05, "2": 0.01, "3": 0, "4": 0 },
          confidence: 0.9,
        },
        next: "Surface this complaint so someone can investigate the problem.",
      },
    ],
  },
  {
    id: "sort-study-notes",
    title: "Organise study notes",
    description: "Give each note a subject label, so the right revision material is easier to find.",
    group: "everyday",
    type: "choice",
    icon: "book",
    questionId: "subject",
    instructions: "Which school subject best matches the main topic of this note?",
    criteria: {
      biology: "Living organisms, cells, plants, or ecosystems.",
      history: "Past events, civilisations, or historical people.",
      physics: "Forces, motion, electricity, or energy.",
      other: "Another subject, or not enough information.",
    },
    from: "a study note",
    to: "biology",
    tags: "education learning homework classification notes school",
    variants: [
      {
        name: "Biology",
        state: "Plants use sunlight, water, and carbon dioxide to make glucose during photosynthesis.",
        answer: {
          type: "choice",
          choice: "biology",
          probabilities: { biology: 0.98, history: 0, physics: 0.01, other: 0.01 },
          confidence: 0.95,
        },
        next: "Add a biology label so the note appears in that revision folder.",
      },
      {
        name: "Physics",
        state: "A force can change an object's speed or direction. Forces are measured in newtons.",
        answer: {
          type: "choice",
          choice: "physics",
          probabilities: { biology: 0, history: 0, physics: 0.99, other: 0.01 },
          confidence: 0.97,
        },
        next: "Add this note to the physics collection.",
      },
    ],
  },
  {
    id: "find-refund-request",
    title: "Find refund requests",
    description: "Check one clear thing: is the customer actually asking for their money back?",
    group: "support",
    type: "noul",
    icon: "receipt",
    questionId: "refund_requested",
    instructions: "Does the customer explicitly request money back or a refund?",
    from: "customer text",
    to: "yes probability",
    tags: "refund return payment billing request noul",
    variants: [
      {
        name: "Money back",
        state: "The kettle arrived broken. Please refund my order rather than sending a replacement.",
        answer: { type: "noul", noul: 0.99 },
        next: "Send this to the refund-help flow, without issuing a refund automatically.",
      },
      {
        name: "Replacement",
        state: "The kettle arrived broken. Could you please send a replacement? I don't want a refund.",
        answer: { type: "noul", noul: 0.02 },
        next: "Look for a replacement workflow instead of assuming a refund is wanted.",
      },
    ],
  },
  {
    id: "pick-agent-tool",
    title: "Choose an agent tool",
    description: "Match a request to an available tool. Keep the actual tool call in your code.",
    group: "developers",
    type: "choice",
    icon: "route",
    questionId: "tool",
    instructions: "Which available tool is the best fit for this request? Choose no_tool if neither tool is needed.",
    criteria: {
      calculator: "Calculate a mathematical expression or numeric result.",
      web_search: "Look up information that requires a current external source.",
      no_tool: "Neither calculation nor external lookup is needed.",
    },
    from: "user request",
    to: "calculator",
    tags: "agents routing function tool select mcp automation developer",
    variants: [
      {
        name: "Calculation",
        state: "What is 18 percent of 240?",
        answer: {
          type: "choice",
          choice: "calculator",
          probabilities: { calculator: 0.99, web_search: 0, no_tool: 0.01 },
          confidence: 0.97,
        },
        next: "Have your code validate the request before calling the calculator.",
      },
      {
        name: "No tool",
        state: "Say hello in a friendly way.",
        answer: {
          type: "choice",
          choice: "no_tool",
          probabilities: { calculator: 0, web_search: 0.01, no_tool: 0.99 },
          confidence: 0.97,
        },
        next: "Let the conversational model answer without calling a tool.",
      },
    ],
  },
  {
    id: "label-product",
    title: "Label a product",
    description: "Turn a product description into one of your shop's own categories.",
    group: "everyday",
    type: "choice",
    icon: "tag",
    questionId: "category",
    instructions: "Which category best describes the product being sold?",
    criteria: {
      clothing: "Clothes and garments worn on the body.",
      electronics: "Electronic devices and powered accessories.",
      home: "Household items that are not clothes or electronics.",
      other: "A product not covered by the other categories.",
    },
    from: "product text",
    to: "clothing",
    tags: "shop ecommerce catalogue taxonomy classify shopping retail",
    variants: [
      {
        name: "A hoodie",
        state: "A soft cotton hoodie with an embroidered mountain design, available in sizes XS to XL.",
        answer: {
          type: "choice",
          choice: "clothing",
          probabilities: { clothing: 0.99, electronics: 0, home: 0, other: 0.01 },
          confidence: 0.97,
        },
        next: "Suggest the clothing category for the catalogue editor to check.",
      },
    ],
  },
  {
    id: "check-claim",
    title: "Check a claim",
    description: "Compare a claim with the source you provide, rather than asking the model to guess.",
    group: "developers",
    type: "noul",
    icon: "file-check",
    questionId: "claim_supported",
    instructions: "Does the provided source support the claim? Use only the source, not outside knowledge.",
    from: "source + claim",
    to: "yes probability",
    tags: "rag citation verify source support claim document grounding",
    variants: [
      {
        name: "Supported",
        state: "Source: The library is open Monday to Friday, from 9am to 6pm. It is closed at weekends.\n\nClaim: The library is closed on Sunday.",
        answer: { type: "noul", noul: 0.99 },
        next: "Keep the claim with its source for a reader to verify.",
      },
      {
        name: "Not supported",
        state: "Source: The library is open Monday to Friday, from 9am to 6pm. It is closed at weekends.\n\nClaim: The library opens at 8am on Saturday.",
        answer: { type: "noul", noul: 0.01 },
        next: "Flag the claim for review; don't present it as supported by this source.",
      },
    ],
  },
  {
    id: "triage-bug",
    title: "Triage a bug report",
    description: "Distinguish a visual glitch from a broken feature with a small, explicit severity scale.",
    group: "developers",
    type: "score",
    icon: "bug",
    questionId: "severity",
    instructions: "How much does the reported bug prevent the user from using an essential feature?",
    criteria: [
      "Cosmetic: appearance or wording is wrong, but the feature works.",
      "Degraded: a feature fails, but the user describes a working alternative.",
      "Blocking: an essential feature fails and no working alternative is described.",
    ],
    from: "bug report",
    to: "severity score",
    tags: "bug incident issue developer severity priority triage",
    variants: [
      {
        name: "Blocking",
        state: "Nobody on the team can log in. Every attempt returns an error, and there is no other way to access our work.",
        answer: {
          type: "score",
          score: 2,
          legend: {
            "0": "Cosmetic: appearance or wording is wrong, but the feature works.",
            "1": "Degraded: a feature fails, but the user describes a working alternative.",
            "2": "Blocking: an essential feature fails and no working alternative is described.",
          },
          probabilities: { "0": 0, "1": 0, "2": 1 },
          confidence: 1,
        },
        next: "Ask a maintainer to review this as a potentially blocking issue.",
      },
      {
        name: "Cosmetic",
        state: "The save button is a few pixels off-centre, but it still saves correctly.",
        answer: {
          type: "score",
          score: 0.02,
          legend: {
            "0": "Cosmetic: appearance or wording is wrong, but the feature works.",
            "1": "Degraded: a feature fails, but the user describes a working alternative.",
            "2": "Blocking: an essential feature fails and no working alternative is described.",
          },
          probabilities: { "0": 0.98, "1": 0.02, "2": 0 },
          confidence: 0.95,
        },
        next: "Keep this with cosmetic reports rather than escalating it as an outage.",
      },
    ],
  },
];

export const FEATURED_PRESET_IDS = ["route-support", "spot-urgency", "rate-review"];

